CREATE TABLE `T_ACCOUNT_EVENT` (
  `FB_ACCOUNT_ID` VARCHAR(127) NOT NULL,
  `EVENT_ID` INT NOT NULL,
  PRIMARY KEY (`FB_ACCOUNT_ID`, `EVENT_ID`),
  FOREIGN KEY (FB_ACCOUNT_ID) REFERENCES `T_ACCOUNT`(FB_ACCOUNT_ID),
  FOREIGN KEY (EVENT_ID) REFERENCES `T_EVENT`(EVENT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;