CREATE TABLE `T_ACCOUNT` (
  `FB_ACCOUNT_ID` VARCHAR(127) NOT NULL PRIMARY KEY,
  `SELF_POS_ID` TINYINT NOT NULL,
  `SEARCH_POS_ID` TINYINT NOT NULL,
  `SEARCH_DESCRIPTION` VARCHAR(127) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `T_ACCOUNT`
ADD CONSTRAINT FK_SELF_POS_ID
FOREIGN KEY (SELF_POS_ID) REFERENCES `T_POSITION`(POS_ID);

ALTER TABLE `T_ACCOUNT`
ADD CONSTRAINT FK_SEARCH_POS_ID
FOREIGN KEY (SEARCH_POS_ID) REFERENCES `T_POSITION`(POS_ID);