CREATE TABLE `T_POSITION` (
  `POS_ID` TINYINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `POS_DESCRIPTION` VARCHAR(127) NOT NULL,
  `POS_ORDER` TINYINT NOT NULL DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `T_POSITION`(`POS_DESCRIPTION`) VALUES ('копирайтер');
INSERT INTO `T_POSITION`(`POS_DESCRIPTION`) VALUES ('арт-директор');

commit;