CREATE TABLE `T_ACCOUNT_REF` (
  `FB_ACCOUNT_ID` VARCHAR(127) NOT NULL,
  `REF_FULL` VARCHAR(127) NOT NULL,
  `IS_TELEGRAM` BOOL NOT NULL DEFAULT FALSE,
  PRIMARY KEY (`FB_ACCOUNT_ID`, `REF_FULL`),
  FOREIGN KEY (FB_ACCOUNT_ID) REFERENCES  `T_ACCOUNT`(FB_ACCOUNT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;